/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;
import Interface.RelatorioCurso;
import Classes.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author César
 */
public class RelatorioCurso extends javax.swing.JFrame {

    /**
     * Creates new form RelatorioAlunos
     */
    public RelatorioCurso() {
        initComponents();
        
        Colecao cursos = Colecao.getInstancia();
        
        for(Curso curso: cursos.getCursos()){
            // faça algo com cada aluno
            DefaultTableModel tabela = (DefaultTableModel) tabelaCurso.getModel();
            
            Object[] novoCurso = new Object[]{
                curso.getNome(),
                curso.getCod(),
                curso.getNumeroAlunos(),
                curso.getNomeProfessor()
            };
            
          tabela.addRow(novoCurso);
            
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCurso = new javax.swing.JTable();
        saveToFile = new javax.swing.JButton();
        saveToFile1 = new javax.swing.JButton();
        saveToFile2 = new javax.swing.JButton();
        saveToFileCursos = new javax.swing.JButton();
        saveToFile3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatorio Alunos");
        setBackground(new java.awt.Color(50, 50, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Relatório de Cusos");

        tabelaCurso.setBackground(new java.awt.Color(110, 110, 110));
        tabelaCurso.setForeground(new java.awt.Color(255, 255, 255));
        tabelaCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome Curso", "Código Curso", "Número de Alunos", "Professor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaCurso);

        saveToFile.setText("Salvar em arquivo");
        saveToFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToFileActionPerformed(evt);
            }
        });

        saveToFile1.setText("Salvar em arquivo");
        saveToFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToFile1ActionPerformed(evt);
            }
        });

        saveToFile2.setText("Salvar em arquivo");
        saveToFile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToFile2ActionPerformed(evt);
            }
        });

        saveToFileCursos.setBackground(new java.awt.Color(50, 50, 50));
        saveToFileCursos.setForeground(new java.awt.Color(255, 255, 255));
        saveToFileCursos.setText("Salvar em arquivo");
        saveToFileCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToFileCursosActionPerformed(evt);
            }
        });

        saveToFile3.setText("Salvar em arquivo");
        saveToFile3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToFile3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(116, 116, 116)
                        .addComponent(saveToFileCursos))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(260, 260, 260)
                    .addComponent(saveToFile)
                    .addContainerGap(260, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(270, Short.MAX_VALUE)
                    .addComponent(saveToFile1)
                    .addGap(250, 250, 250)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(280, Short.MAX_VALUE)
                    .addComponent(saveToFile2)
                    .addGap(240, 240, 240)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(260, 260, 260)
                    .addComponent(saveToFile3)
                    .addContainerGap(260, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(saveToFileCursos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(157, 157, 157)
                    .addComponent(saveToFile)
                    .addContainerGap(158, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(167, Short.MAX_VALUE)
                    .addComponent(saveToFile1)
                    .addGap(148, 148, 148)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(177, Short.MAX_VALUE)
                    .addComponent(saveToFile2)
                    .addGap(138, 138, 138)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(157, 157, 157)
                    .addComponent(saveToFile3)
                    .addContainerGap(158, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveToFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToFileActionPerformed
        // TODO add your handling code here:
        Colecao cursos = Colecao.getInstancia();
        cursos.salvarDados();
    }//GEN-LAST:event_saveToFileActionPerformed

    private void saveToFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToFile1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveToFile1ActionPerformed

    private void saveToFile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToFile2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveToFile2ActionPerformed

    private void saveToFileCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToFileCursosActionPerformed
        // TODO add your handling code here:
        Colecao cursos = Colecao.getInstancia();
        cursos.salvarDados();
    }//GEN-LAST:event_saveToFileCursosActionPerformed

    private void saveToFile3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToFile3ActionPerformed
        // TODO add your handling code here:
        Colecao cursos = Colecao.getInstancia();
        cursos.salvarDados();
    }//GEN-LAST:event_saveToFile3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveToFile;
    private javax.swing.JButton saveToFile1;
    private javax.swing.JButton saveToFile2;
    private javax.swing.JButton saveToFile3;
    private javax.swing.JButton saveToFileCursos;
    private javax.swing.JTable tabelaCurso;
    // End of variables declaration//GEN-END:variables
}
